---
- name: Copy, run, and cleanup tool on target machines
  hosts: tool
  #gather_facts: false
  become: yes
# test variables
  vars:
    ansible_user: "jcw2555"
    ansible_password: "Password!"
    source_file: "~/redteamtool/sneakytool.sh"  
    destination_dir: "/home/tool" 

  tasks:
# Ensure teh destination directory exists
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ destination_dir }}"
        state: directory
        mode: '0755'

# copy the tool to the destination directory on the target machines
    - name: Copy files from host to target machines
      ansible.builtin.copy:
        src: "{{ source_file }}"
        dest: "{{ destination_dir }}"
        owner: root
        group: root
        mode: '0644'

# Change the permissions of the tool
  - name: Modify file permissions
    file:
      path: /home/tool/sneakytool.sh
      mode: u+x

# Modify the sshd_config file
  # Modify PasswordAuthentication variable
  - name: Set PasswordAuthentication to yes
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: 'PasswordAuthentication no'
      line: 'PasswordAuthentication yes'
      state: present

  # Modify UsePAM variable
  - name: Set UsePAM to yes
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: 'UsePAM no'
      line: 'UsePAM yes'
      state: present

# Run the bash script found in the github repository
  - name: Execute script
    command: sh /home/tool/sneakytool.sh

# Delete the github folder and all its contents
  - name: Delete folder with tool
    file:
      path: /home/tool
      state: absent